Repository Susmita-Dey/TextUtils, pull requests merged in 2022-10, with the labels that each got.

#22 added github link to footer
  src/components/Footer.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, approved

#25 Added Link Extractor
  src/components/TextForm.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, approved

#19 added SentenceCase button
  src/App.js
  src/components/Footer.js
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted, approved

#23 Added white space removal feature
  src/components/TextForm.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, approved

#24 added contributor image in readme
  README.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted, approved

#35 Add confirm before clearing the text
  src/components/TextForm.js
Labels: enhancement, hacktoberfest-accepted, approved

#36 Make "Stop now" and "Listen now" into one button. (#29)
  src/components/TextForm.js
Labels: enhancement, hacktoberfest-accepted, approved

#67 Added the Speech To Text Button
  src/components/TextForm.js
Labels: enhancement, hacktoberfest-accepted, approved

#73 Reverse button added
  src/components/TextForm.js
Labels: enhancement, hacktoberfest-accepted, approved

#58 added Base64 encoding
  package-lock.json
  package.json
  src/components/TextForm.js
Labels: enhancement, hacktoberfest-accepted, approved

#75 Modified the about section
  package-lock.json
  src/components/About.js
Labels: enhancement, hacktoberfest-accepted

#79 updated the text summary and added more details
  README.md
  src/components/TextForm.js
Labels: enhancement, hacktoberfest-accepted, approved

#82 created add text button
  src/components/TextForm.js
Labels: enhancement, hacktoberfest-accepted, approved

#85 Remove special characters button added
  src/components/TextForm.js
Labels: enhancement, hacktoberfest-accepted

#87 Update README.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted

#86 Undo/redo the actions performed on the text, resolves Susmita-Dey/Tex…
  package-lock.json
  src/components/TextForm.js
  src/index.js
  src/reducers/textReducer.jsx
Labels: enhancement, hacktoberfest-accepted, approved

#94 Modified the footer section
  package-lock.json
  package.json
  src/components/Footer.js
Labels: enhancement, hacktoberfest-accepted, approved

#95 Capitalized all text forms
  src/components/TextForm.js
Labels: enhancement, hacktoberfest-accepted, approved

#101 add prettier config file
  .prettierignore
  .prettierrc
Labels: hacktoberfest-accepted

#92 Clean code enhancement
  README.md
  package-lock.json
  package.json
  src/App.js
  src/components/About.js
  src/components/Alert.js
  src/components/ErrorPage.js
  src/components/Footer.js
  src/components/Navbar.js
  src/components/TextForm.js
  src/components/ui/Button.jsx
  src/helper/capitalize.js
  src/index.js
  src/reducers/textReducer.jsx
  src/store/alertMessages.json
  src/store/features/alert/alertSlice.js
  src/store/features/text/textSlice.js
  src/store/features/theme/themeSlice.js
  src/store/store.js
Labels: enhancement, hacktoberfest-accepted, approved
